# set the default PCAP_ROOT value
IF(NOT PCAP_ROOT)
  SET(PCAP_ROOT $ENV{PCAP_ROOT} CACHE PATH "The PCAP directory root.")
ENDIF(NOT PCAP_ROOT)

FIND_LIBRARY(PCAP_LIBRARY
  NAMES wpcap
  PATHS
    ${PCAP_ROOT}/Lib
  DOC "The PCAP library")

FIND_PATH(PCAP_INCLUDE_DIR
  NAMES pcap.h
  PATHS
    ${PCAP_ROOT}/Include
  DOC "The PCAP include files")

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(PCAP DEFAULT_MSG
  PCAP_LIBRARY PCAP_INCLUDE_DIR)
