//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by dllmodule.rc
//
#define IDS_ADDON_NAME                  100
#define IDR_SCSTUDIO                    101
#define IDS_ERROR_VISIO_VERSION         101
#define IDS_VSL_NAME                    102
#define IDS_REPORT_VIEW                 103
#define IDD_ABOUTBOX                    203
#define IDD_FIND_FLOW                   204
#define IDD_CHECK_OPTIONS               205
#define IDC_ABOUT_VERSION               205
#define IDC_CHECKLIST                   206
#define IDD_SIMULATOR_OPTIONS           206
#define IDC_OUTPUTLEVEL                 207
#define IDD_INSTANCES_FIELD_OPTIONS     207
#define IDC_DRAWING1                    208
#define IDC_CHANNELTYPE                 208
#define IDC_DRAWING2                    209
#define IDI_ICON_CHECK                  209
#define IDI_ICON_FIND_FLOW              210
#define IDI_ICON_SELECT_INSTANCES       211
#define IDI_ICON_SELECT_MESSAGES        212
#define IDI_ICON_SIMULATION_START       213
#define IDI_ICON_SIMULATION_STOP        214
#define IDC_SIM_MESSAGE_DELAY           218
#define IDI_ICON_SELECT_ADD_INSTANCES   218
#define IDC_SIM_BIN_WIDTH               219
#define IDI_ICON_SELECT_ADD_MESSAGES    219
#define IDC_IF_INSTANCES_CNT            220
#define IDD_MESSAGE_SEQUENCE_OPTIONS    220
#define IDC_IF_MARGIN_SIDE              221
#define IDC_IF_INSTANCE_LENGTH          221
#define IDD_ENUMERATION_OPTIONS         221
#define IDC_IF_MARGIN_TOP               222
#define IDI_MESSAGE_NUMBERING           222
#define IDI_ICON_ENABLE_MESSAGE_ENUMERATION 222
#define IDC_IF_INSTANCES_HEIGHT         223
#define IDC_IF_START_POS_X              223
#define IDI_ICON_DISABLE_MESSAGE_ENUMERATION 223
#define IDI_MESSAGE_NUMBERING_DISABLE   224
#define IDD_NUMBERING_GLOBAL            225
#define IDC_OPTIONS_SWITCH_BTN          226
#define IDC_OPTIONS_SWITCH_LBL          227
#define IDD_DIALOG1                     227
#define IDD_SNAP_GLOBAL                 227
#define IDC_OPTIONS_GROUP_BOX           228
#define IDC_IF_LBL1                     229
#define IDI_ICON_JUMP_LEFT              229
#define IDC_IF_LBL2                     230
#define IDI_ICON_JUMP_RIGHT             230
#define IDC_IF_LBL3                     231
#define IDC_IF_SPACING_SWITCH           232
#define IDD_PROTECTION_GLOBAL           232
#define IDC_IF_SPACING                  233
#define IDI_ICON_JUMP_LEFT_COPY         233
#define IDI_ICON2                       234
#define IDI_ICON_JUMP_RIGHT_COPY        234
#define IDC_IF_MARGIN_LEFT              236
#define IDC_IF_MARGIN_RIGHT             237
#define IDB_BITMAP1                     237
#define IDD_DIALOG2                     238
#define IDC_IF_LBL4                     239
#define IDC_IF_LBL5                     240
#define IDC_IF_START_POS_Y              241
#define IDC_TOTAL_WIDTH_RDO             242
#define IDC_RADIO2                      243
#define IDC_SPACING_RDO                 243
#define IDC_MS_DIR_RIGHT                243
#define IDC_DONT_NUMBER                 243
#define IDC_PRESERVE_VERTICAL           243
#define IDC_FIRST_INSTANCE_RDO          243
#define IDC_IF_TOTAL_WIDTH              244
#define IDC_FIRST_HEAD_RDO              244
#define IDC_DEFAULT_BTN                 245
#define IDC_FIRST_COREGION_RDO          246
#define IDD_BEAUTIFY_SETTINGS           247
#define IDB_GOING_BACK_BMP              250
#define IDC_MS_DIR_LEFT                 251
#define IDB_INSTANCES_DISTANCES_BMP     251
#define IDC_MS_DIR_LEFT_RIGHT           252
#define IDC_COMBO_NUMBERING             252
#define IDB_CROSSING_BMP                252
#define IDC_ADDITION                    253
#define IDB_CROSSING_GOING_BACK_BMP     253
#define IDC_MS_LEFT_MESSAGE             254
#define IDC_CHECK_ENUMERATE_NEW         254
#define IDC_EDGE_THREATMENT_ENABLED     254
#define IDC_SETTING_SPACE               254
#define IDD_IMPORT_SETTINGS             254
#define IDC_MS_RIGHT_MESSAGE            255
#define IDC_STARTING_INDEX              255
#define IDB_IMPORT_DISTANCES_BMP        255
#define IDC_MS_YSTART                   256
#define IDC_MS_START_POS_Y              256
#define IDI_ICON1                       256
#define IDI_ICON_SELECT_GROUP           256
#define IDC_MS_VERTICAL_SPACE           257
#define IDI_ICON_BEAUTIFY               257
#define IDC_MS_DIR_RIGHT_LEFT           258
#define IDI_ICON_MESSAGE_SEQUENCE       258
#define IDC_MS_VERTICAL_SPACE2          259
#define IDC_MS_VERTICAL_SPACE_LEFT_RIGHT 259
#define IDI_ICON_REVERSE_MESSAGE        259
#define IDC_MS_UNITS0                   260
#define IDI_ICON6                       260
#define IDI_ICON_TIGHTEN_TIME           260
#define IDC_MS_UNITS1                   261
#define IDC_IF_UNITS0                   261
#define IDC_MS_UNITS2                   262
#define IDC_IF_UNITS1                   262
#define IDC_MS_COREGION_ERROR           263
#define IDC_MS_COREGION_CONTINUE        264
#define IDC_NEAREST_MSG                 264
#define IDC_MS_COREGION_ORDER           265
#define IDC_TAB2                        265
#define IDC_TAB_SETTINGS                265
#define IDC_RADIO3                      265
#define IDC_NEAREST_NUMBERED_MSG        265
#define IDC_PRESERVE_SLOPE              265
#define IDC_ORIGINAL_INSTANCE_RDO       265
#define IDI_ICON3                       265
#define IDI_ICON_ADD_INSTANCES          265
#define IDC_IF_UNITS2                   267
#define IDC_IF_UNITS3                   268
#define IDC_MS_CONNECT_WITH_LINE        268
#define IDC_IF_UNITS4                   269
#define IDC_MS_CONNECT_WITH_SIDE_SIDE   269
#define IDC_CHECK2                      271
#define IDC_ENUM_CHECK                  271
#define IDC_ONLY_ON_LINE                271
#define IDC_KEYS_ENABLED                271
#define IDC_RADIO4                      273
#define IDC_USE_NUMBERING_STYLE         273
#define IDC_PARTS_INSTANCE_RDO          273
#define IDC_COMBO_NUMBERING_GLOBAL      276
#define IDC_ADDITION_GLOBAL             277
#define IDC_STARTING_INDEX_GLOBAL       278
#define IDC_CHECK1                      279
#define IDC_SNAP_ENABLED                279
#define IDC_DONT_ROTATE_CHECK           279
#define IDC_ARRANGING                   279
#define IDC_DIFF                        279
#define IDC_SETTING_HEAD                280
#define IDC_SETTING_COREGION            281
#define IDC_MSG_TYPE                    282
#define IDC_LEFT_INST_CHECK             285
#define IDC_RIGHT_INST_CHECK            286
#define IDC_CUSTOM1                     287
#define IDC_RADIO1                      288
#define IDC_STRAIGHTEN                  288
#define IDC_CONST_INSTANCE_RDO          288
#define IDC_BUTTONS_ENABLED             289
#define IDC_CONST_COREGION_RDO          290
#define IDC_EDGE_PRESERVE_TYPE          291
#define IDC_EDGE_CHANGE_TYPE            292
#define IDC_CONST_HEAD_RDO              299
#define IDC_ORIGINAL_ORDER_RDO          312
#define IDC_CROSSING_ORDER_RDO          313
#define IDC_GOING_BACK_ORDER_RDO        314
#define IDC_BOTH_ORDER_RDO              315
#define IDC_COR_WIDTH_VALUE             318
#define IDC_HEAD_WIDTH_VALUE            320
#define IDC_HEAD_DIST_VALUE             321
#define IDC_INCOMPLETE_MSG_VALUE        322
#define IDC_SLOPE_VALUE                 323
#define IDC_SUCCESSOR_DIST_VALUE        324
#define IDC_FOOT_DIST_VALUE             325
#define IDC_SPACE_VALUE                 326
#define IDC_INSTANCE_LENGTH_VALUE       327
#define IDC_BEGIN_COR_DIST_VALUE        328
#define IDC_END_COR_DIST_VALUE          329
#define IDC_HEAD_DIST_VALUE_IMP         331
#define IDB_BEGIN_COR_DIST_VALUE_IMP    332
#define IDC_BEGIN_COR_DIST_VALUE_IMP    332
#define IDC_HEAD_WIDTH_VALUE_IMP        333
#define IDC_INCOMPLETE_MSG_VALUE_IMP    334
#define IDC_FOOT_DIST_VALUE_IMP         335
#define IDC_SLOPE_VALUE_IMP             336
#define IDC_SPACE_VALUE_IMP             337
#define IDC_COR_WIDTH_VALUE_IMP         338
#define IDC_END_COR_DIST_VALUE_IMP      339
#define IDC_SUCCESSOR_DIST_VALUE_IMP    340

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        267
#define _APS_NEXT_COMMAND_VALUE         32768
#define _APS_NEXT_CONTROL_VALUE         342
#define _APS_NEXT_SYMED_VALUE           105
#endif
#endif
