#
# scstudio - Sequence Chart Studio
# http://scstudio.sourceforge.net
#
#      This library is free software; you can redistribute it and/or
#      modify it under the terms of the GNU Lesser General Public
#      License version 2.1, as published by the Free Software Foundation.
#
#      This library is distributed in the hope that it will be useful,
#      but WITHOUT ANY WARRANTY; without even the implied warranty of
#      MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#      Lesser General Public License for more details.
#
# Copyright (c) 2009 Petr Gotthard <petr.gotthard@centrum.cz>
#
# $Id: diacritics_build.py 243 2009-05-03 19:05:14Z gotthardp $

import csv

array = {}

# download from http://unicode.org/Public/UNIDATA/UnicodeData.txt
# see http://unicode.org/Public/UNIDATA/UCD.html
unicodeData = csv.reader(open('UnicodeData.txt'), delimiter=';')
for row in unicodeData:
  uchar = int(row[0],16)

  # inspect unicode character decomposition
  # decomposed [a-zA-Z] characters are considered equivalent to the wchar
  codes = row[5].split(' ')
  for c in codes:
    try:
      ch = int(c,16)
    except:
      ch = None

    # check if this wchar is decomposed to [a-zA-Z]
    # the table is built only for unicode character 0..1024
    if uchar < 1024 and (ch >= ord('a') and ch <= ord('z') or ch >= ord('A') and ch <= ord('Z')):
      array[uchar] = chr(ch)

minimum = min(array.keys())
maximum = max(array.keys())

file = open("strip_diacritics.cpp", 'wt')

file.write('''
// Generated by diacritics_build.py. Do not edit!
#include "data/msc_types.h"

static char transliteration_table[''' + str(maximum-minimum+1) + '''] = {
''')

for x in range(minimum,maximum+1):
  try:
    file.write("'" + array[x] + "'")
  except:
    file.write("0")

  if x < maximum:
    file.write(",")

  if (x-minimum+1) % 16 == 0:
    file.write("\n")

file.write("};\n")

file.write('''
char strip_diacritics(wchar_t ch)
{
  if(ch < ''' + str(minimum) + ' || ch > ' + str(maximum) + ''')
    return 0;

  // lookup equivalent character
  return transliteration_table[ch-''' + str(minimum) + '''];
}
''')

file.close()

# $Id: diacritics_build.py 243 2009-05-03 19:05:14Z gotthardp $
